In [1]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\user\miniconda3\lib\site-packages (3.9.3)
Requirement already satisfied: click in c:\users\user\miniconda3\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\user\miniconda3\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\users\user\miniconda3\lib\site-packages (from nltk) (2026.2.28)
Requirement already satisfied: tqdm in c:\users\user\miniconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\user\miniconda3\lib\site-packages (from click->nltk) (0.4.6)

In [4]:
from nltk.tokenize import word_tokenize
import pandas as pd

In [8]:
#load the data 
df = pd.read_csv(r"C:\Users\USER\Documents\PBA\SentimentAnalysis\planner_clean_reviews.csv")
df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,review_length
0,6d130fcb-47b1-42fc-a032-bf97719ca5a4,Alexander Benkstein,https://play-lh.googleusercontent.com/a-/ALV-U...,principally good app pretty much unusable your...,2,0,1.18.36,2026-03-03 15:08:44,NaN,NaN,1.18.36,190
1,34f4642b-17ee-463b-ac28-05a902db1cb9,Thomas Watson,https://play-lh.googleusercontent.com/a/ACg8oc...,like far ill report later,3,0,1.18.36,2026-02-27 11:03:15,NaN,NaN,1.18.36,42
2,5a9342d9-8259-4c6f-b8b8-20b1096cf69d,Matt Winter,https://play-lh.googleusercontent.com/a-/ALV-U...,would load real assistance common days easier ...,1,1,1.18.36,2026-02-27 05:43:15,NaN,NaN,1.18.36,257
3,73a714db-ceb1-4b5d-a1af-64d953643ad9,Hugo Arista,https://play-lh.googleusercontent.com/a/ACg8oc...,experience app really good thing tools availab...,4,0,1.18.36,2026-02-24 23:49:27,NaN,NaN,1.18.36,252
4,79b2321f-1e26-4028-b553-da8b0d8896b4,Laura R,https://play-lh.googleusercontent.com/a-/ALV-U...,app complete failure planner used kanban board...,1,1,1.18.33,2026-02-17 05:10:32,NaN,NaN,1.18.33,490

In [9]:
#load only content 
df["content"].head()
content = df["content"]

0    principally good app pretty much unusable your...
1                            like far ill report later
2    would load real assistance common days easier ...
3    experience app really good thing tools availab...
4    app complete failure planner used kanban board...
Name: content, dtype: object

In [13]:
import re
#take up some words from nltk 
df = df.dropna(subset=["content"])
df["tokens"] = df["content"].apply(lambda x: x.split())

In [14]:
#print the words
df["tokens"].head()

0    [principally, good, app, pretty, much, unusabl...
1                      [like, far, ill, report, later]
2    [would, load, real, assistance, common, days, ...
3    [experience, app, really, good, thing, tools, ...
4    [app, complete, failure, planner, used, kanban...
Name: tokens, dtype: object

In [17]:
all_text = df["tokens"].explode()
print(all_text)

0        principally
0               good
0                app
0             pretty
0               much
            ...
2835         excited
2835         planner
2835    capabilities
2836           clean
2836          simple
Name: tokens, Length: 25825, dtype: object

In [20]:
tokens_df = all_text.reset_index(drop=True).to_frame(name="token")
tokens_df.head()

         token
0  principally
1         good
2          app
3       pretty
4         much